export const FETCH_HEXAGONS = "FETCH_HEXAGONS";
export const FETCH_ROADS = "FETCH_ROADS";
export const FETCH_SETTLEMENTS = "FETCH_SETTLEMENTS";

export const UPDATE_HEXAGONS = "UPDATE_HEXAGONS";
export const UPDATE_ROADS = "UPDATE_ROADS";
export const UPDATE_SETTLEMENTS = "UPDATE_SETTLEMENTS";

export const UPDATE_PLAYER_ORDER = "UPDATE_PLAYER_ORDER";
export const CHANGE_PLAYER = "CHANGE_PLAYER";
export const CHANGE_TURN = "CHANGE_TURN";
export const SET_SETTLEMENT_BUILT = "SET_SETTLEMENT_BUILT";
export const SET_ROAD_BUILT = "SET_ROAD_BUILT";

export const UPDATE_PLAYERS = "UPDATE_PLAYERS";
